### PR TITLE
Changed state, Multiple checkboxes

### PR DESCRIPTION
**Pull request by ezimir**
Hey!

I had few problems with this:
- when having multiple iPhone styled checkboxes on one page: hovering mouse over other checkboxes while still dragging the first one made the others animate (move indicators) too
- when dragging from Off to On, it only flipped to On when more than half of the length was dragged, but in the other direction, this was not happening (flipped every time, no matter how much was dragged).
- I needed to know whether any change occured or not

This is how I solved it... any use to you?

Martin

PS: my first use of github, I hope I'm doing it the right way

### CODE REVIEW

**Comment by tdreyno** [comment]
Thanks for the commits, I'll dig into these this weekend hopefully.

**Comment by tdreyno** [comment]
First thought, your editor seems to have changed the white-space in the files making the commits very hard to read (lots of whitespace removal and such).

Trying to figure out what actually changed in this commit:
https://github.com/ezimir/iphone-style-checkboxes/commit/29b8ee7d2e90cf1ab9f485de1a9ebb37464dbddc

**Comment by ezimir** [comment]
Well, sorry about that white space, I have vim set to remove trailing spaces on lines automatically. I'm sure there's some diff view where one can ignore whitespace changes (like in Trac), isn't there?

**Comment by tdreyno** [comment]
I'm sorry, but I don't have the time right now to figure out the commit. If you can update the patch/pull request to show just the changes and not the whitespace, I'd be happy to take a look.

**Comment by ezimir** [comment]
You must be quite busy, eh? No time...

Run this in JS console on commit page:
    jQuery.expr[':'].hasX = function(obj) { var $this = $(obj); return ($this.find('.x').length && $this.next().find('.x').length); }; jQuery('.data tbody tr:hasX').toggle().next().toggle();

Or in URL bar like this:
    javascript: ........

Cleares out most of the whitespace changes...

**Comment by tdreyno** [comment]
Applied patches 1 & 2 on the master branch.

**Pull request closed without merging**
