### PR TITLE
Bower support

### PR DESCRIPTION
**Pull request by rajkissu**
- Starts tag at v1.0.0 (semver)
- Adds component.json for Bower integration

### CODE REVIEW

**Comment by tdreyno** [comment]
Cool! Does this mean we have to register with Bower or does it somehow scrape Github?

**Comment by tdreyno** [comment]
Oh, also, how does this handle the CSS/Image components of the plugin?

**Comment by rajkissu** [comment]
We're required to register it manually - run `bower register iphone-style-checkboxes git://github.com/tdreyno/iphone-style-checkboxes.git` and you're good to go. Make sure you tag the commit at the version specified in `component.json` (v1.0.0) on github beforehand though. You can then run `bower install iphone-style-checkboxes` and it'll fetch the files for you.

Bower doesn't handle consumption of dependencies, only low level management. You could write a grunt task plugin to concatenate files and minify them, or use an existing one like [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task).

**Comment by tdreyno** [comment]
Tagged: https://github.com/tdreyno/iphone-style-checkboxes/tree/v1.0.0

And registered.

**Pull request merged**
